<a href="https://colab.research.google.com/github/SiddhantUke/PYTHON_REVISE/blob/main/Sect_13_(56_Data_Manipulation_with_pd_np).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Data Manipulation and Analysis with Pandas

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [6]:
# FOR INSTALLATION OF  LIBRARY !

!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)

In [7]:
import pandas as pd
import numpy as np

In [8]:
df =  df = pd.read_csv("/content/data (2).csv")

## For fetch the first top 5 !

df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [9]:
df.tail()

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [10]:
df.describe()

## here we get statistical analysis that both of we required  !

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [11]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [12]:
## Handling Missing Value !

df.isnull()

# If we are getting True Value then we can say that we have missing value there !

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [13]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [14]:
df.isnull().any()

## Where ever is True Show then there is a missing value basically !

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [15]:
##how to check how many value is missing and where !

df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [16]:
## Where ever the missing value if we used this command then it automatically replace with this zero !

df.fillna(0)

##  0 basically default value !

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [17]:
## How to filled missing value mean of the column !

df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean())

In [18]:
df

## With this statement we actucally filled the missing value !

          Date Category  Value   Product  Sales Region  Sales_fillNA
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [19]:
## LEts the if we want to change the data types !

df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_fillNA    float64
dtype: object

In [20]:

# Sales	float64

## how we convert this value into integer value !

In [21]:
## Renaming Column !

df = df.rename(columns={'Date':'Sales Date'})

df.head()


## Date':'Sales Date'

# This we have to give in the form of key value pair !

   Sales Date Category  Value   Product  Sales Region  Sales_fillNA
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [22]:
df["Value_new"] = df["Value"].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [23]:
## IF I WANT TO CHANGE THE Data Types !

df["Value_new"] = df["Value"].fillna(df["Value"].mean()).astype(int)

df.head()

#fillna(df["Value"].mean()) having missing value and as well as the

## Df of value and replaced it with mean !

   Sales Date Category  Value   Product  Sales Region  Sales_fillNA  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26

In [24]:
## What if i want to apply the funtn with another column !

df["New Value"]  = df ['Value'].apply(lambda x:x*2)

In [25]:
df

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.000000,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.000000,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.000000,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.000000,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.000000,26,52.0
5,2023-01-06,B,54.0,Product3,192.0,West,192.000000,54,108.0
6,2023-01-07,A,16.0,Product1,936.0,East,936.000000,16,32.0
7,2023-01-08,C,89.0,Product1,488.0,West,488.000000,89,178.0
8,2023-01-09,C,37.0,Product3,772.0,West,772.000000,37,74.0
9,2023-01-10,A,22.0,Product2,834.0,West,834.000000,22,44.0
10,2023-01-11,B,7.0,Product1,842.0,North,842.000000,7,14.0
11,2023-01-12,B,60.0,Product2,NaN,West,557.130435,60,120.0
12,2023-01-13,A,70.0,Product3,628.0,South,628.000000,70,140.0
13,2023-01-14,A,69.0,Product1,423.0,East,423.000000,69,138.0
14,2023-01-15,A,47.0,Product2,893.0,West,893.000000,47,94.0
15,2023-01-16,C,NaN,Product1,895.0,North,895.000000,51,NaN
16,2023-01-17,C,93.0,Product2,511.0,South,511.000000,93,186.0
17,2023-01-18,C,NaN,Product1,108.0,West,108.000000,51,NaN
18,2023-01-19,A,31.0,Product2,578.0,West,578.000000,31,62.0
19,2023-01-20,A,59.0,Product1,736.0,East,736.000000,59,118.0
20,2023-01-21,C,82.0,Product3,606.0,South,606.000000,82,164.0
21,2023-01-22,C,37.0,Product2,992.0,South,992.000000,37,74.0
22,2023-01-23,B,62.0,Product3,942.0,North,942.000000,62,124.0
23,2023-01-24,C,92.0,Product2,342.0,West,342.000000,92,184.0
24,2023-01-25,A,24.0,Product2,458.0,East,458.000000,24,48.0
25,2023-01-26,C,95.0,Product1,584.0,West,584.000000,95,190.0
26,2023-01-27,C,71.0,Product2,619.0,North,619.000000,71,142.0
27,2023-01-28,C,56.0,Product2,224.0,North,224.000000,56,112.0
28,2023-01-29,B,NaN,Product3,617.0,North,617.000000,51,NaN
29,2023-01-30,C,51.0,Product2,737.0,South,737.000000,51,102.0
30,2023-01-31,B,50.0,Product3,735.0,West,735.000000,50,100.0
31,2023-02-01,A,17.0,Product2,189.0,West,189.000000,17,34.0
32,2023-02-02,B,63.0,Product3,338.0,South,338.000000,63,126.0
33,2023-02-03,C,27.0,Product3,NaN,East,557.130435,27,54.0
34,2023-02-04,C,70.0,Product3,669.0,West,669.000000,70,140.0
35,2023-02-05,B,60.0,Product2,NaN,West,557.130435,60,120.0
36,2023-02-06,C,36.0,Product3,177.0,East,177.000000,36,72.0
37,2023-02-07,C,2.0,Product1,NaN,North,557.130435,2,4.0
38,2023-02-08,C,94.0,Product1,408.0,South,408.000000,94,188.0
39,2023-02-09,A,62.0,Product1,155.0,West,155.000000,62,124.0
40,2023-02-10,B,15.0,Product1,578.0,East,578.000000,15,30.0
41,2023-02-11,C,97.0,Product1,256.0,East,256.000000,97,194.0
42,2023-02-12,A,93.0,Product3,164.0,West,164.000000,93,186.0
43,2023-02-13,A,43.0,Product3,949.0,East,949.000000,43,86.0
44,2023-02-14,A,96.0,Product3,830.0,East,830.000000,96,192.0
45,2023-02-15,B,99.0,Product2,599.0,West,599.000000,99,198.0
46,2023-02-16,B,6.0,Product1,938.0,South,938.000000,6,12.0
47,2023-02-17,B,69.0,Product3,143.0,West,143.000000,69,138.0
48,2023-02-18,C,65.0,Product3,182.0,North,182.000000,65,130.0
49,2023-02-19,C,11.0,Product3,708.0,North,708.000000,11,22.0



---

In [ ]:
## This is Data Manipulation !



---

In [26]:
## Data Aggregating  and Grouping !

df.head()

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [27]:
## Product ----> Vased on this we are actually do the mean of this specific value !

grouped_mean=df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [28]:
## I want to do groupby based on the categorical variables !

## Product and Region !

grouped_sum=df.groupby(['Product','Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [29]:

## Actucally a mean  of the upper "Product" and "Region"

df.groupby(['Product','Region'])['Value'].mean()

Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [30]:
## Aggregaet Multiple Functn !

## aggregate multiple functions


groudped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
groudped_agg

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17



---

In [ ]:
##Merging  and Joining Dataframe !

##Create Simple DataFrames

In [31]:
### Merging and joining Dataframes
# Create sample DataFrames


df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [32]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [33]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [34]:
## Merge Dataframes on the 'Key Columns'

pd.merge(df1,df2,on="Key",home = 'inner')

## on="Key" --------> Basically means on which columns name !

## Outer -----------> Both dataframe is consider and probably each row and column is considered !

## Left Outer Join -------------> df1 will given more priority that is given in dataframe !

## RIght --------> Right  side key is more important

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [35]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [36]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [37]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6